version: "2"

services:
    back-order-v3:
        image: 495665774687.dkr.ecr.eu-north-1.amazonaws.com/back-kotlin-test:latest
        network_mode: "host"
        ports:
            - 8080:8080
        environment:
            - SERVICE_PORT=8080
        logging:
            driver: awslogs
            options:
                awslogs-group: ecs-dev-task-group
                awslogs-region: eu-north-1
                awslogs-stream-prefix: ecs

