name: Kotlin CI with Maven

on:
  push:
    branches: [ "dev" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2

    - uses: actions/checkout@v2

    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17

    - name: Build with Maven
      run: mvn -B package --file pom.xml
